jQuery.ajaxSetup({traditional:!0});$(document).data("userSelection",{projectId:null,protocolId:null,cosmology:null,boxLength:null,phisicId:null,resolution:null,snapshotId:null,simulationId:null,simulationName:null,objectType:null,postProcessorId:null,linkingLength:null,postProcessingId:null,clientMail:null,displayPageSize:100,datasetSize:1E3,sortOrder:"ASC",sortCriterion:null});$(document).data("extractFunction",null);RsB=new ResultSetBrowser($(document).data("userSelection").displayPageSize,$(document).data("userSelection").datasetSize);
function getRandomId(d){d=16<d?16:d;randId="";for(var h=0;h<d;)if(value=Math.floor(123*Math.random()),48<=value&&57>=value||65<=value&&90>=value||97<=value&&122>=value)randId+=String.fromCharCode(value),h++;return randId}function normalizeStr(d){d=d.toLowerCase();d=d.replace(/\s+/g,"_");d=d.replace(/[^a-z]+/g,"");return d=d.replace(/[^a-z0-9_\.]/g,"")}function toFixed(d,h){var c=Math.pow(10,h||0);return""+Math.round(d*c)/c}
function beautifulNumber(d,h){return 1E3>d?toFixed(d,h):d.toExponential(2)}
jQuery(document).ready(function(){function d(a){$("#"+a).empty()}function h(a){$("#"+a+" option").each(function(a,b){$(b).remove()})}function c(){"none"==$("#loading").css("display")&&($("#loading").css("display","block"),$(document).mousemove(function(a){milieu=$("#loading").width()/2;$("#loading").css({left:a.pageX,top:a.pageY-2*milieu})}))}function t(a){tips.text(a).addClass("ui-state-highlight");setTimeout(function(){tips.removeClass("ui-state-highlight",1500)},500)}function u(){var a=["Lambda",
"Ratra-Peebles","Sugra"];d("cosmology");$.getJSON("ajax/availableParameterSettingForInputParameterProtocolProject",{inputParameterName:"Dark energy type",protocolId:$(document).data("userSelection").protocolId,projectId:$(document).data("userSelection").projectId},function(f){var b="";jQuery.each(f,function(f,c){0==f?(b=b.concat("<option value='"+c.numericvalue_value+"' selected>"+a[c.numericvalue_value-1]+"</option>"),$(document).data("userSelection").cosmology=c.numericvalue_value):b=b.concat("<option value='"+
c.numericvalue_value+"'>"+a[c.numericvalue_value-1]+"</option>")});$("#cosmology").append(b)})}function g(){d("physic");$.getJSON("ajax/availablePhysicsByProtocol",{protocolId:$(document).data("userSelection").protocolId},function(a){jQuery.each(a,function(a,b){0==a?($("#physic").append("<option value='"+b.id+"' name='"+b.name+"' selected>"+b.name+"</option>"),$(document).data("userSelection").physicId=b.id):$("#physic").append("<option value='"+b.id+"' name='"+b.name+"'>"+b.name+"</option>");$("option[name='"+
b.name+"']").qtip({content:b.description,style:{name:"deuvostyle"},position:{target:"mouse"},show:{solo:!0}})})})}function p(){d("boxLength");$.getJSON("ajax/availableParameterSettingForInputParameterCosmologyProtocol",{inputParameterName:"Boxlength",protocolId:$(document).data("userSelection").protocolId,projectId:$(document).data("userSelection").projectId,cosmology:$(document).data("userSelection").cosmology},function(a){jQuery.each(a,function(a,b){"dimensionless"==b.numericvalue_unit&&(b.numericvalue_unit=
"");0==a?($("#boxLength").append("<option value='"+b.numericvalue_value+"' selected>"+b.numericvalue_value+" "+b.numericvalue_unit+"</option>"),$(document).data("userSelection").boxLength=b.numericvalue_value):$("#boxLength").append("<option value='"+b.numericvalue_value+"'>"+b.numericvalue_value+" "+b.numericvalue_unit+"</option>")});j()})}function j(){d("resolution");$.getJSON("ajax/availableResolutionForCosmologyBoxlengthProtocol",{protocolId:$(document).data("userSelection").protocolId,cosmology:$(document).data("userSelection").cosmology,
boxlength:$(document).data("userSelection").boxLength},function(a){jQuery.each(a,function(a,b){"dimensionless"==b.numericvalue_unit&&(b.numericvalue_unit="");0==a?($("#resolution").append("<option value='"+b.numericvalue_value+"' selected>"+b.numericvalue_value+" "+b.numericvalue_unit+"</option>"),$(document).data("userSelection").resolution=b.numericvalue_value):$("#resolution").append("<option value='"+b.numericvalue_value+"'>"+b.numericvalue_value+" "+b.numericvalue_unit+"</option>")})})}function k(){var a=
0;0<$("#simulationParameterSettings").height()&&(a=$("#simulationParameterSettings").height(),$("#simulationParameterSettings").height(a));$("#matchingSimulations").val()&&$.getJSON("ajax/parameterSettingForExperiment",{experimentId:$("#matchingSimulations").val()},function(a){jQuery.each(a,function(b,a){"dimensionless"==a.numericvalue_unit&&(a.numericvalue_unit="");1==b%2?$("#simulationParameterSettings").append('<tr><td><div name="'+a.name+'">'+a.name+"</div></td><td>"+beautifulNumber(a.numericvalue_value,
2)+" "+a.numericvalue_unit+"</td></tr>"):$("#simulationParameterSettings").append('<tr style="background:none repeat scroll 0 0 #ddf1ff"><td><div name="'+a.name+'">'+a.name+"</div></td><td>"+beautifulNumber(a.numericvalue_value,2)+" "+a.numericvalue_unit+"</td></tr>");$("div[name='"+a.name+"']").qtip({content:a.description,style:{name:"deuvostyle"},position:{target:"mouse"},show:{solo:!0}})})});$("#simulationParameterSettings tr").remove()}function q(){d("matchingSimulations");jQuery.post("querySimulations",
{cosmology:$(document).data("userSelection").cosmology,physic:$(document).data("userSelection").physicId,protocol:$(document).data("userSelection").protocolId,boxLength:$(document).data("userSelection").boxLength,resolution:$(document).data("userSelection").resolution},function(a){jQuery.each(a,function(a,b){var c=toFixed(b.redshift,2);0==a?($("#matchingSimulations").append("<option value='"+b.id+"' name='"+b.name+"_snapid_"+b.snapshotid+"' selected>z = "+c+"</option>"),$(document).data("userSelection").simulationId=
b.id,$(document).data("userSelection").simulationName=b.name,/.+_snapid_([0-9]+)$/.exec($("#matchingSimulations option:selected").attr("name")),$(document).data("userSelection").snapshotId=RegExp.$1):$("#matchingSimulations").append("<option value='"+b.id+"' name='"+b.name+"_snapid_"+b.snapshotid+"'>z = "+c+"</option>");$("option[name='"+b.name+"']").qtip({content:b.description,style:{name:"deuvostyle"},position:{target:"mouse"},show:{solo:!0}})});k();n()},"json")}function n(){h("objectType");$("#matchingSimulations").val()&&
$.getJSON("ajax/availableObjectTypeForExperiment",{experimentId:$(document).data("userSelection").simulationId},function(a){jQuery.each(a,function(a,b){0==a?($("#objectType").append("<option value='"+b.name+"' name='"+b.name+"' selected>"+b.name+"</option>"),$(document).data("userSelection").objectType=b.name):$("#objectType").append("<option value='"+b.name+"' name='"+b.name+"' >"+b.name+"</option>");$("option[name='"+b.name+"']").qtip({content:b.description,style:{name:"deuvostyle"},position:{target:"mouse"},
show:{solo:!0}});$("option[name='"+b.name+"']").qtip({content:b.description,style:{name:"deuvostyle"},position:{target:"mouse"},show:{solo:!0}})});1==a.length&&l()})}function l(){h("postprocessor");$.getJSON("ajax/availablePostProcessorForExperimentObjectType",{experimentId:$(document).data("userSelection").simulationId,objectTypeName:$(document).data("userSelection").objectType},function(a){jQuery.each(a,function(a,b){0==a?($("#postprocessor").append("<option value='"+b.id+"' name='"+b.name+"' selected>"+
b.name+"</option>"),$(document).data("userSelection").postProcessorId=b.id):$("#postprocessor").append("<option value='"+b.id+"' name='"+b.name+"' >"+b.name+"</option>");$("option[name='"+b.name+"']").qtip({content:b.description,style:{name:"deuvostyle"},position:{target:"mouse"},show:{solo:!0}})});for($(document).data("userSelection").postprocParamsSetting=[];0<$("#postprocessor").queue().length;);1==a.length&&e()})}function m(a){var f=[];$.ajax({url:"ajax/getAvailableInputParametersByProtocol",
dataType:"json",data:{protocolId:a},async:!1,success:function(b){jQuery.each(b,function(b,a){var c={};c.id=a.id;c.name=a.name;c.description=a.description;f.push(c)})}});return f}function e(){d("postprocParams");paramsList=m($(document).data("userSelection").postProcessorId);for(jQuery.each(paramsList,function(a,c){0==a?$("#postprocParams").append("<option name='"+c.name+"' value='"+c.id+"' selected>"+c.name+"</option>"):$("#postprocParams").append("<option name='"+c.name+"' value='"+c.id+"'>"+c.name+
"</option>");$("option[name='"+c.name+"']").qtip({content:c.description,style:{name:"deuvostyle"},position:{target:"mouse"},show:{solo:!0}})});0<$("#postprocParams").queue().length;);1==paramsList.length&&v()}function v(){d("postprocParamValues");var a=$("#postprocParams").val();$.ajax({url:"ajax/availableParameterSettingForParameterPostprocessorParent",dataType:"json",data:{inputParameterId:a,protocolId:$(document).data("userSelection").postProcessorId,snapshotId:$(document).data("userSelection").snapshotId},
success:function(c){jQuery.each(c,function(b,c){0==b?($("#postprocParamValues").append("<option  value='"+c.numericvalue_value+"' selected>"+c.numericvalue_value+"</option>"),$(document).data("userSelection").postprocParamsSetting[a]=c.numericvalue_value):$("#postprocParamValues").append("<option  value='"+c.numericvalue_value+"'>"+c.numericvalue_value+"</option>")})}})}function x(){d("matchingPostprocessings");var a=0,c=$(document).data("userSelection").postprocParamsSetting,b;for(b in c){a=c[b];
break}jQuery.post("queryPostprocessing",{experimentId:$(document).data("userSelection").simulationId,snapshotId:$(document).data("userSelection").snapshotId,postprocessorId:$(document).data("userSelection").postProcessorId,inputParamId:b,inputParamSetting:a},function(b){jQuery.each(b,function(b,a){0==b?($("#matchingPostprocessings").append("<option value='"+a.id+"' name='"+a.name+"' selected>"+a.name+"</option>"),$(document).data("userSelection").postProcessingId=a.id):$("#matchingPostprocessings").append("<option value='"+
a.id+"' name='"+a.name+"'>"+a.name+"</option>");$("option[name='"+a.name+"']").qtip({content:a.description,style:{name:"deuvostyle"},position:{target:"mouse"},show:{solo:!0}})});0==b.length?($("#matchingPostprocessingTr").hide(),$("#propertiesRangeQueryDiv").hide(),$("#matchingProductsDiv").hide()):(w(),y())},"json")}function w(){$("#postprocessingParameterSettings tr").remove();$.getJSON("ajax/parameterSettingForExperiment",{experimentId:$(document).data("userSelection").postProcessingId},function(a){jQuery.each(a,
function(a,b){"dimensionless"==b.numericvalue_unit&&(b.numericvalue_unit="");1==a%2?$("#postprocessingParameterSettings").append('<tr><td><div name="'+b.name+'">'+b.name+"</div></td><td>"+b.numericvalue_value.toFixed(2)+" "+b.numericvalue_unit+"</td></tr>"):$("#postprocessingParameterSettings").append('<tr style="background:none repeat scroll 0 0 #ddf1ff"><td><div name="'+b.name+'">'+b.name+"</div></td><td>"+beautifulNumber(b.numericvalue_value,2)+" "+b.numericvalue_unit+"</td></tr>");$("div[name='"+
b.name+"']").qtip({content:b.description,style:{name:"deuvostyle"},position:{target:"mouse"},show:{solo:!0}})})});$.getJSON("ajax/diskCacheExperimentData",{experimentId:$(document).data("userSelection").postProcessingId,normalizedObjecttype:normalizeStr($(document).data("userSelection").objectType)},function(){})}function y(){$.getJSON("ajax/propertiesAndStatsExperimentObjecttype",{objecttypeName:$(document).data("userSelection").objectType,experimentId:$(document).data("userSelection").postProcessingId},
function(a){$("#propertiesRangeQueryTable").empty();for(var c="<tr>\n<th>Property</th>\n<th>greater than</th>\n<th>lower than</th>\n",b=0;b<o.length;b++)c+="<th>"+o[b]+"</th>\n";c+="<th>View in result</th>\n";$("#propertiesRangeQueryTable").append(c+"</tr>\n");jQuery.each(a,function(a,c){var d=c.unit.search(/dimensionless/i)?"<i><small>("+c.unit+")</small></i>":"",f='<tr><td><div name="'+c.propName+'">'+c.propName+" "+d+"</div></td>\n",f=f+('<td><input id="iptmin'+c.colName+'" type="text"/></td>\n'),
f=f+('<td><input id="iptmax'+c.colName+'" type="text"/></td>\n');for(b=0;b<o.length;b++){var z=RegExp(o[b]+"\\s+.+","i"),e=!1;jQuery.each(c.statList,function(b,a){if(z.test(a.name))return e=!0,f+='<td><div="'+a.name+'">'+beautifulNumber(a.numericvalue_value,2)+"</div></td>\n",!1});e||(f+="<td>n/a</td>\n")}f=0>jQuery.inArray(c.colName,r)?f+('<td><input type="checkbox" value="'+c.colName+'"/></td>\n'):f+"<td>yes</td>\n";f+="</tr>";$("#propertiesRangeQueryTable").append(f+"\n");$("div[name='"+c.propName+
"']").qtip({content:c.propDescription,style:{name:"deuvostyle"},position:{target:"mouse"},show:{solo:!0}})})})}function s(a){"undefined"==typeof a&&(a=1);i=r;var c=[],b=[],d=[];$("#propertiesRangeQueryDiv input:checkbox:checked").each(function(){d.push($(this).val())});i=i.concat(d);if(0<i.length){RsB.propertyNameToDisplayList=i.slice();var b=i,e="",g="";null!=$(document).data("userSelection").sortCriterion&&(e=$(document).data("userSelection").sortCriterion,g=$(document).data("userSelection").sortOrder);
RsB.sortCriterion=e;RsB.sortOrder=g;$('input[id^="ipt"]').each(function(b,a){var d="",e=$(a).attr("id");if($(a).val()){var g=$(a).val(),h=e.replace(/ipt(min|max)/,"");-1!=e.search("iptmin")&&(d=h+" > "+g);-1!=e.search("iptmax")&&(d=h+" < "+g)}""!=d&&c.push(d)});$(document).data("whereList",c);jQuery.post("queryProductsTAP",{experimentId:$(document).data("userSelection").postProcessingId,whereList:c,selectList:b,orderbyClause:e,orderClause:g,normalizedObjecttype:normalizeStr($(document).data("userSelection").objectType),
pageNo:a,itemsPerPage:$(document).data("userSelection").datasetSize},function(b){$("#matchingProducts thead tr").remove();$("#matchingProducts tbody tr").remove();$("#productDownloadLink").html("");$("#productsPager").html("");if(0==b.resultCount)$("#productsNumber").html("<br/>There is not any result for your request");else{$("#productsNumber").html("There are "+b.resultCount+" matching objects ");$("#productDownloadLink").html('<a name="launchExtraction" style="cursor:pointer;" >Extract selected Halos</a>');
$("#productDownloadLink a[name='launchExtraction']").click(function(){var b=void 0;"undefined"!=typeof b&&b?$(document).data("extractFunction",A):0<$('input:checkbox[name="downloadParticles"]:checked').length?($(document).data("extractFunction",B),$("#email-form").dialog("open")):$("#extraction-error-selection").dialog("open")});var c=b.productList;if(0<c.length){for(var d="<tr>",f=0;f<i.length;f++)d=d.concat('<th name="prod_list_header_'+i[f]+'" style="cursor:pointer;"><u>'+i[f]+"</u></th>");d=d.concat('<th>wanted particles<br/><span name="none"  onclick="javascript:toggleSelectProduct($(this),\'downloadParticles\')"><u>(select all)</u></span></th>');
$("#matchingProducts thead").html(d.concat("</tr>"));RsB.resultSetList=c.slice();$("#matchingProducts tbody").empty();RsB.showProductsPage(1,a)}c=Math.random().toString();c=c.substring(c.lastIndexOf(".")+1);c=' | <img id="deuvoHubStatusIcon" src="resources/images/samp/disconnected.png" onclick="deuvoSamp.toggleConnection();"/>'+(" <a name='broadcast2SampLink' title='samp' href='javascript:void(0);' onclick=\"javascript:WebSampConnector.sendMsg('table.load.votable','','','"+b.productListVotableURL+
"','')\"';>Broadcast VOTable through SAMP</a>");""!=b.productListTextURL&&(c+=" | <a href='"+b.productListTextURL+"'>Download Text File</a>\n");""!=b.productListVotableURL&&(c+=" | <a href='"+b.productListVotableURL+"' target='_blank'>Download Votable</a>\n");$("#productDownloadLink").append(c+"<br/>TopCat : <a href='http://www.star.bris.ac.uk/~mbt/topcat/' onclick=\"MM_openBrWindow('http://www.star.bris.ac.uk/~mbt/topcat/','topcat download','scrollbars=yes,width=650,height=500'); return false;\">Download</a> | <a href='http://www.star.bris.ac.uk/~mbt/topcat/topcat-lite.jnlp'>Launch</a>");
$("#deuvoHubStatusIcon").qtip({content:"Click to connect/disconnect to Samp Bus. Samp is a protocol to share data among VO applications. As an example, you can run TopCat, then click this link to make Deuvo send data to TopCat",style:{name:"deuvostyle"},position:{target:"mouse"},show:{solo:!0,delay:0,effect:{length:0}}});$("a[name='broadcast2SampLink']").qtip({content:"Send selected data to Samp enabled application. The Samp enabled application (like Topcat) must be started before broadcasting data",
style:{name:"deuvostyle"},position:{target:"mouse"},show:{solo:!0,delay:0,effect:{length:0}}})}},"json")}else alert("At least one property must be checked")}function A(){$(document).data("userSelection").clientMail||($(document).data("userSelection").clientMail="david.languignon@obspm.fr");jQuery.post("ajax/extractAllFoundObjects",{experimentId:$("#matchingPostprocessings").val(),whereClause:$(document).data("whereClause"),orderbyClause:$(document).data("orderbyClause"),normalizedObjecttype:normalizeStr($("#objectType").val()),
snapshotId:$(document).data("userSelection").snapshotId,simulationName:$(document).data("userSelection").simulationName,clientMail:$(document).data("userSelection").clientMail},function(a){$("#job_group_id").html(a.groupId);$("#extraction-started").dialog("open")},"json")}function B(){if(0<$('input:checkbox[name="downloadParticles"]:checked').length){$(document).data("userSelection").clientMail||($(document).data("userSelection").clientMail="david.languignon@obspm.fr");var a=[];$('input:checkbox[name="downloadParticles"]:checked').each(function(c,
b){a.push($(b).val())});jQuery.post("ajax/extractUserSelectedObjects",{coordsList:a,experimentId:$("#matchingPostprocessings").val(),normalizedObjecttype:normalizeStr($("#objectType").val()),snapshotId:$(document).data("userSelection").snapshotId,simulationName:$(document).data("userSelection").simulationName,clientMail:$(document).data("userSelection").clientMail},function(a){$("#job_group_id").html(a.groupId);$("#extraction-started").dialog("open")},"json")}else alert("at least one object must be selected")}
RsB.submitQueryProductFunc=s;$.fn.qtip.styles.deuvostyle={width:240,border:{width:1,radius:3}};$.fn.qtip.defaults.show.delay=0;$.fn.qtip.defaults.show.effect.type="grow";$.fn.qtip.defaults.hide.effect.length=30;$(".accordion").click(function(){$(this).next().toggle("slow");return!1});$("#loading").ajaxStart(function(){c()});$("#loading").ajaxStop(function(){$("#loading").css("display","none");$(document).unbind("mousemove")});tips=$(".validateTips");$("#email-form").dialog({autoOpen:!1,modal:!0,buttons:{"Extract Halos' particles":function(){var a=
$("#email"),c;c=!0;80<a.val().length||6>a.val().length?(a.addClass("ui-state-error"),t("Length of email must be between 6 and 80."),c=!1):c=!0;c&&(/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i.test(a.val())?
c=!0:(a.addClass("ui-state-error"),t("eg. ui@jquery.com"),c=!1));c?($(document).data("userSelection").clientMail=a.val(),$(document).data("extractFunction")(),$(this).dialog("close")):a.val("email not valid, retry")},Cancel:function(){$(this).dialog("close")}},close:function(){}});$("#extraction-started").dialog({autoOpen:!1});$("#extraction-error-selection").dialog({autoOpen:!1});$(document).data("userSelection").projectId=$("#project").val();(function(){d("protocol");$.getJSON("ajax/availableSimulatorByProject",
{projectId:$(document).data("userSelection").projectId},function(a){var c=0;jQuery.each(a,function(b,a){c=b;0==b?($("#protocol").append("<option name='"+a.name+"' value='"+a.id+"' selected>"+a.name+"</option>"),$(document).data("userSelection").protocolId=a.id):$("#protocol").append("<option name='"+a.name+"' value='"+a.id+"' >"+a.name+"</option>");$("option[name='"+a.name+"']").qtip({content:a.description,style:{name:"deuvostyle"},position:{target:"mouse"},show:{solo:!0}})});0==c&&$("#protocol").attr("disabled",
"disabled")})})();$("#protocol").ajaxSuccess(function(a,c,b){-1!=b.url.search("ajax/availableSimulatorByProject")&&(u(),g())});$("#protocol").change(function(){u();g()});$("#cosmology").click(function(){$(document).data("userSelection").cosmology=$("#cosmology").val();p()});$("#physic").click(function(){$(document).data("userSelection").physicId=$("#physic").val()});$("#boxLength").click(function(){$(document).data("userSelection").boxLength=$("#boxLength").val();j()});$("#resolution").click(function(){$(document).data("userSelection").resolution=
$("#resolution").val()});$("#1FormButton").click(function(){$(document).data("userSelection").physicId&&$(document).data("userSelection").cosmology&&$(document).data("userSelection").protocolId&&$(document).data("userSelection").boxLength&&$(document).data("userSelection").resolution&&(q(),"none"==$("#matchingSimulationsDiv").css("display")&&$("#matchingSimulationsDiv").show())});$("#matchingSimulations").live("click",function(){$(document).data("userSelection").simulationId=$("#matchingSimulations").val();
/^(.+)_snapid_[0-9]+$/.exec($("#matchingSimulations option:selected").attr("name"));$(document).data("userSelection").simulationName=RegExp.$1;/.+_snapid_([0-9]+)$/.exec($("#matchingSimulations option:selected").attr("name"));$(document).data("userSelection").snapshotId=RegExp.$1});$("#objectType").live("click",function(){$(document).data("userSelection").objectType=$("#objectType").val();l()});$("#postprocessor").live("click",function(){$(document).data("userSelection").postProcessorId=$("#postprocessor").val();
e()});$("#postprocParams").live("click",function(){v()});$("#postprocParamValues").live("click",function(){var a=$("#postprocParams").val();$(document).data("userSelection").postprocParamsSetting[a]=$("#postprocParamValues").val()});$("#matchingPostprocessings").live("click",function(){$(document).data("userSelection").postProcessingId=$("#matchingPostprocessings").val();w();sortCriterion=$(document).data("userSelection").sortCriterion=null});$("#2FormButton").click(function(){$(document).data("userSelection").objectType&&
$(document).data("userSelection").postProcessorId&&$(document).data("userSelection").postprocParamsSetting&&(x(),"none"==$("#matchingPostprocessingTr").css("display")&&$("#matchingPostprocessingTr").show())});var o=["Min","Mean","Max"],r=["x","y","z"];$("button[name=searchMatchingObject]").click(function(){s()});var i=r;$('th[name^="prod_list_header_"]').live("click",function(){var a=$(this).attr("name").slice(17);$(document).data("userSelection").sortCriterion==a?(newSortOrder="ASC"==$(document).data("userSelection").sortOrder?
"DESC":"ASC",$(document).data("userSelection").sortOrder=newSortOrder):$(document).data("userSelection").sortCriterion=a;s()})});
function ResultSetBrowser(d,h){var c=this===window?{}:this;c.domTableId="#matchingProducts";c.domPagerId="#productsPager";c.propertyNameToDisplayList=[];c.resultSetList=[];c.sortCriterion="";c.sortOrder="ASC";c.submitQueryProductFunc=null;c.displayPageSize="undefined"==typeof d?100:d;c.datasetSize=h;c.sortProductsBy=function(d){c.sortCriterion==d?c.sortOrder="ASC"==c.sortOrder?"DESC":"ASC":c.sortCriterion=d;c.submitQueryProductFunc()};c.showProductsPage=function(d,h){var g=c.displayPageSize,p=c.datasetSize,
j=c.resultSetList.length,k=j*(h-1)/g,q=d+k,n=k+j/g;0<j%g&&n++;if(0==$(c.domTableId+" tbody tr").length){for(var l=0;l<j;l++){var m=c.resultSetList[l],e='<tr class="page'+(0==l?1:Math.ceil(l/g))+'" style="display:none">';jQuery.each(c.propertyNameToDisplayList,function(c,d){e=e.concat("<td>"+beautifulNumber(m[d],2)+"</td>")});e=e.concat('<td><input type="checkbox"name="downloadParticles" value="'+m.x+"|#|"+m.y+"|#|"+m.z+'"></td>');$(c.domTableId+" tbody").append(e.concat("</tr>"))}c.showProductsPage(d,
h)}else $(c.domTableId+" tbody tr").css("display","none"),$(c.domTableId+" tbody tr.page"+d).css("display","");$(c.domPagerId).empty();e="";0!=k&&(e=e.concat("<a href='javascript:RsB.submitQueryProductFunc("+(h-1)+")'> <b><u>previous...</u></b></a>,"));for(g=k+1;g<=n;g++)e=g!=q?e.concat("<a href='javascript:RsB.showProductsPage("+(g-k)+","+h+")'> "+g+"</a>,"):e.concat("<a href='javascript:RsB.showProductsPage("+(g-k)+","+h+")'> <b><u>"+g+"</u></b></a>,");j==p&&(e=e.concat("<a href='javascript:RsB.submitQueryProductFunc("+
(h+1)+")'> <b><u>more...</u></b></a>,"));$(c.domPagerId).append(e.concat())}};
